import { EventCard } from "../components/EventCard";
import { Footer } from "../components/Footer";
import { Navbar } from "../components/Navbar";
import { PageHero } from "../components/PageHero";
import sawa from '../assets/gallery/WhatsAppImage2024-06-15at17.46.23.jpeg';
import picha02 from '../assets/gallery/WhatsAppImage2024-06-15at17.46.44.jpeg';
// import picha03 from '../assets/gallery/WhatsAppImage2024-06-15at17.46.43.jpeg';
import beach from '../assets/gallery/WhatsAppImage2024-06-15at17.46.29.jpeg';
import  school from '../assets/gallery/school.jpg';
import  autism from '../assets/gallery/IMG-20240516-WA0118.jpg';
import  hedhi from '../assets/gallery/IMG-20240516-WA0105.jpg';
import  sanaa from '../assets/gallery/IMG-20240516-WA0052.jpg';
import  tabasam from '../assets/gallery/IMG-20240514-WA0014.jpg';
import  wazee from '../assets/gallery/IMG-20240516-WA0056.jpg';
import  miti from '../assets/gallery/IMG-20240516-WA0073.jpg';
export const Events = () => {
    const eventLIsts = [
        { id: 1, name: 'NI SAWA NA MIMI', image: sawa, isCompleted: true, date: '2022-02-02', description: '"Ni Sawa Na Mimi" is an initiative by Nibadilishe that advocatesfor equality and fights against discrimination towards individualswith special needs or belonging to marginalized groups.Thephrase "Ni Sawa Na Mimi" translates to English “It\'s the same as me" in Swahili, emphasizing the belief that every individual, regardless of their background, abilities, or circumstances,deserves equal rights, respect, and opportunities.Through this initiative, Nibadilishe works to raise awareness about the importance of inclusion, diversity, and acceptance in society.The goal is to create a more inclusive and equitable community where everyone can live with dignity and thrive to their fullest potential, free from prejudice and discrimination.', },
        { id: 2, name: 'NISITIRI BINTI CAMPAIGN', image: picha02, isCompleted: true, date: '2023-02-22', description: 'The "Nisitiri Binti" campaign is centered around the donation of underwear to girls and women in need. By providing clean and quality underwear, the campaign aims to address a fundamental aspect of menstrual hygiene management and empower girls and women to navigate their periods with comfort and dignity.' },
        { id: 3, name: 'FLASH BACK TO SCHOOL', image: school, isCompleted: true, date: '2024-02-12', description: '"Flashback to School" is an initiative by Nibadilishe that focuses on providing all the necessary school materials to children from low-income communities. The aim of this campaign is to ensure that every child has access to quality education by removing the financial barrier associated with purchasing school supplies. Through "Flashback to School," Nibadilishe distributes items such as textbooks, notebooks, stationery, backpacks, and uniforms to students in need, enabling them to fully engage in their learning and pursue their academic goals. By addressing the material needs of these students, the campaign seeks to promote educational equity and empower children from marginalized backgrounds to reach their full potential.' },
        { id: 4, name: 'SANAA CHARITY EVENT', image: sanaa, isCompleted: true, date: '2024-02-12', description: 'The "Sanaa Charity Event" is a special occasion organized by Nibadilishe to showcase the talents of orphans and vulnerable children. Through this event, Nibadilishe provides a platform for these children to express themselves creatively through various forms of art, such as music, dance, drama, painting, and poetry. The event not only celebrates the unique talents and abilities of these children but also raises awareness about their needs and challenges. Additionally, the "Sanaa Charity Event" serves as a fundraiser to support programs and initiatives aimed at improving the lives of orphans, including educational support, healthcare, and psychosocial services. By harnessing the power of art and community support, Nibadilishe strives to uplift and empower orphaned and vulnerable children, giving them hope for a brighter future.' },
        { id: 5, name: 'AUTISIM AWARENESS', image: autism, isCompleted: true, date: '2024-02-12', description: 'The Autism Awareness Event is an initiative organized by Nibadilishe to increase understanding and acceptance of autism spectrum disorder (ASD) within the community. This event aims to raise awareness about autism, dispel myths and misconceptions, and promote acceptance and inclusion of individuals with autism. Activities at the event may include informational sessions, panel discussions featuring individuals with autism and their families, art exhibitions showcasing the talents of individuals with autism, and interactive workshops on supporting individuals with ASD. The Autism Awareness Event provides a platform for education, dialogue, and advocacy, fostering a more inclusive and supportive environment for individuals with autism and their families.' },
        { id: 6, name: 'SIKU ZANGU FAHARI YANGU', image: hedhi, isCompleted: true, date: '2024-02-12', description:'"Siku Zangu, Fahari Yangu" (My Days, My Pride) is an event organized by Nibadilishe to celebrate Menstrual Hygiene Day. This event aims to raise awareness about menstrual hygiene management and break the stigma surrounding menstruation. Through this event, Nibadilishe empowers girls and women to embrace their menstrual cycles with pride and dignity, while also advocating for improved access to menstrual hygiene products, facilities, and education. The event highlights the importance of destigmatizing menstruation and ensuring that every individual can manage their periods safely, comfortably, and with confidence.'},
        { id: 7, name: 'PANDA MTI', image: miti, isCompleted: true, date: '2024-02-12', description:'"Panda Mti" (Plant a Tree) is an initiative by Nibadilishe aimed at promoting environmental conservation and combating climate change. Through this initiative, volunteers come together to plant trees in various locations, including schools, parks, and community spaces. By planting trees, "Panda Mti" helps to improve air quality, mitigate the effects of deforestation, and create habitats for wildlife. Additionally, the initiative raises awareness about the importance of trees in combating climate change and encourages individuals to take action to protect the environment. "Panda Mti" embodies the spirit of collective responsibility and environmental stewardship, empowering communities to make a positive impact on the planet.'},
        { id: 8, name: 'NG’ARISHA TABASAMU LAO', image: tabasam, isCompleted: true, date: '2024-02-12', description:'"Nga\'risha Tabasamu Lao" (Brighten Their Smiles) is an initiative by Nibadilishe that involves painting orphanage centers to create vibrant and welcoming environments for children. Through this initiative, volunteers come together to repaint the walls of orphanages with colorful and uplifting designs, including murals, patterns, and inspirational messages. By transforming the physical spaces where children live and play, "Nga\'risha Tabasamu Lao" aims to bring joy and positivity into their lives. The initiative not only enhances the aesthetic appeal of orphanage centers but also fosters a sense of belonging and pride among the children. Through the power of art and community engagement, "Nga\'risha Tabasamu Lao" brightens the smiles of children in need and creates lasting impressions of hope and happines'},
        { id: 9, name: 'BEACH CLEAN UP', image: beach, isCompleted: true, date: '2024-02-12', description:'The Beach Clean-Up initiative is a community-driven effort organized by Nibadilishe to promote environmental sustainability and combat plastic pollution. This event brings together volunteers of all ages to gather at local beaches and remove litter and debris from the shoreline. Participants are provided with gloves, bags, and other cleaning materials to collect trash such as plastic bottles, wrappers, and other waste. The Beach Clean-Up not only helps to beautify the coastline but also raises awareness about the importance of keeping our oceans and beaches clean. By engaging in this hands-on activity, volunteers contribute to the preservation of marine ecosystems and the protection of wildlife habitats. Additionally, the event serves as a platform for education and advocacy, inspiring individuals to adopt more sustainable practices in their daily lives and become stewards of the environment.'},
        { id: 10, name: 'JALI WAZEE', image: wazee, isCompleted: true, date: '2024-02-12', description:'Jali wazeeinitiative by nibadilishe organization aim to visit elderly individuals in need at dar es saalam'},
      ]
    return (
        <div>
            <PageHero
                page="Events"
                title="Events"
                description="NIBADILISHE Our upcoming & completed events Lorem"
            />
            <div className="max-w-[1200px] mx-auto">
                <div className="grid grid-cols-1 mx-auto gap-3 md:grid-cols-3 px-3 justify-center md:justify-between">
                    {eventLIsts.map((items)=><EventCard key={items.id} picture={items.image} name={items.name} date={items.date} description={items.description} isCompleted={items.isCompleted} />)}
                    
                </div>
            </div>
        </div>
    )
}
